### ISSUE TITLE
Failing while 'Adding to Wanted'

### ISSUE THREAD

**Issue by pcooney4** [RhinoRhys/radarr-collections#121] opened 2021-10-25 00:23 UTC
I'm getting the following when running -f scan.  Running in docker pulled today.  Any help appreciated.  

```
[21-10-25 00:00:15] >>                     TMDB ID: 8077      Alien³ (1992)                                                                                                    > Rejected: Blacklisted
[21-10-25 00:00:15] >>                     TMDB ID: 8078      Alien Resurrection (1997)                                                                                        Adding to Wanted
Traceback (most recent call last):
  File "/app/rcm.py", line 522, in <module>
    else: tmdb_check(movie["tmdbId"]) 
  File "/app/rcm.py", line 288, in tmdb_check
    collection_check(col_id, tmdbId)
  File "/app/rcm.py", line 276, in collection_check
    for id_check in parts:  database_check(id_check, white_name, col_json, input_id)
  File "/app/rcm.py", line 199, in database_check
    path = "/".join(rootpath, folder)
TypeError: str.join() takes exactly one argument (2 given)
Found 0 Movies
```

**Comment by RhinoRhys** [comment] 2021-11-03 21:51
dupe of #119 

fixed with todays update :)

**Closed by RhinoRhys** 2021-11-03 21:51 UTC
